use_frameworks!
platform :ios, '9.0'

target 'RxInfinitePicker_Example' do
  pod 'InfinitePicker', :path => '../'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'ShapeView'

  target 'RxInfinitePicker_Tests' do
    inherit! :search_paths
  end
end
